config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get 'privacy_policy', to: 'pages#privacy_policy', as: 'privacy_policy'

  get '/apps/favorite', to: 'apps#favorite', as: 'favorite_apps'
  get '/apps/shared/:public_token', to: 'apps#shared_apps'
  get '/bookmarks/create_multiple', to: 'bookmarks#create_multiple', as: 'create_multiple_bookmarks'
  resources :apps, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:create ]
  end
  resources :bookmarks, only: [:destroy]
  get 'apps/:app_id/bookmark', to: 'bookmarks#create', as: "bookmarkerr"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Google Authentication
  get '/google_oauth2/get_google_access_code', to: 'google_authentications#get_google_access_code'
  get '/google_oauth2/callback', to: 'google_authentications#callback'
end

app/views/shared/_bookmark-alert.html.erb
<div class="bookmark-alert">
</div>

app/views/shared/_favorite-list.html.erb
<% apps.each do |app| %>
  <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
    <%= link_to app.webpage_url, target: "_blank" do %>
      <!-- boite principale -->
      <div class="app-card__fav">
        <!-- background box -->
        <div class="app-card__visible" style="background-image: url('<%= app.logo %>')">
          <!-- hovered part -->
        </div>
          <% if app.integrated%>
            <div class="app-card__notification">
             <%= @gmail_response %>
            </div>
          <% end %>
          <%= link_to app_path(app) do %>
             <%= image_tag 'card-icons/info-icon.png', class: "app-card__hidden fav-icon__info" %>
          <% end %>
          <%= link_to bookmark_path(current_user.bookmarks.where(app: app)[0]), method: "delete" do %>
            <%= image_tag 'card-icons/trash-icon.png', class: "app-card__hidden fav-icon__trash" %>
          <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-made-by">
    Made with <i class="fas fa-heart"></i> &  <i class="fas fa-coffee"></i> by <a href="https://www.linkedin.com/in/jlbdcn/" target="_blank" >Julien</a>, <a href="https://www.linkedin.com/in/jan-s-16a187154/" target="_blank"> Jan</a>, <a href="https://www.linkedin.com/in/jackjoconnor" target="_blank">Jack</a> and <a href="" target="_blank" > Sebastien</a>
  </div>
  <div class="footer-copyright">
      <p> © 2018 | Noora </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <% unless controller_name == 'apps' && action_name == 'index' || controller_name == 'apps' && action_name == 'favorite' || controller_name == 'apps' && action_name == 'show' %>
      <%= image_tag "NOORA_logo.png", height: 50 %>
    <% end %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i> <%= t("Edit profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-cog"></i> <%= t("Edit profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_review.html.erb
<div class="review">
  <div class="review-header">
    <%= cl_image_tag review.user.avatar_url, class: "review__avatar" %>
    <div>
      <p class="review__user"><b><%= review.user.username.capitalize! %></b> on <%= l(review.created_at, format: :month_year) %></p>
      <p class="review__ratings">
        <% review.rating.times do %>
          <i class="fa fa-star" aria-hidden="true"></i>
        <% end %>
      </p>
    </div>
  </div>
  <p class="review__content"><%= review.content %></p>

</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar sidebar__sticky">
  <div class="sidebar__logo">
    <%= link_to apps_path do %>
      <span class="sidebar__logo-unhovered"><%= image_tag "NOORA_logo_small.png", height: 50 %></span>
      <span class="sidebar__logo-hovered"><%= image_tag "NOORA_logo.png", height: 50 %></span>
    <% end %>
  </div>
    <ul>
      <li class="sidebar__search">
        <div class="sidebar__search-bar">
          <i class="fa fa-search" aria-hidden="true"></i>
          <%= form_tag apps_path, method: :get do %>
            <%= text_field_tag :query,
              params[:query],
              autocomplete: :off,
              class: "form-control form-search sidebar__search-bar-input",
              placeholder: "Find an app..."
            %>
          <% end %>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="sidebar__favorite">
          <%= link_to favorite_apps_path do %>
             <%= image_tag 'category-icons/icon-favorite-on.png', class: "sidebar-icon sidebar-icon-hover" %><%= image_tag 'category-icons/icon-favorite-off.png', class: "sidebar-icon sidebar-icon-no-hover" %></i><span class="sidebar__category-name">Favorites</span>
          <% end %>
        </li>
      <% end %>
        <li class="sidebar__home">
          <%= link_to apps_path do %>
             <%= image_tag 'category-icons/icon-home-on.png', class: "sidebar-icon sidebar-icon-hover" %><%= image_tag 'category-icons/icon-home-off.png', class: "sidebar-icon sidebar-icon-no-hover" %></i><span class="sidebar__category-name">Home</span>
          <% end %>
        </li>
      <% Category.all.each do |category| %>
          <li>
            <%= link_to apps_path(category: category.name) do %>
              <%= image_tag category.icon, class: "sidebar-icon sidebar-icon-no-hover" %><%= image_tag category.icon_hover, class: "sidebar-icon sidebar-icon-hover" %><div class="sidebar__category-name"><%= category.name %></div>
            <% end %>
          </li>
      <% end %>
    </ul>
</div>