config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  get 'privacy_policy', to: 'pages#privacy_policy', as: 'privacy_policy'

  get '/apps/favorite', to: 'apps#favorite', as: 'favorite_apps'
  get '/apps/shared/:public_token', to: 'apps#shared_apps'
  get '/bookmarks/create_multiple', to: 'bookmarks#create_multiple', as: 'create_multiple_bookmarks'
  resources :apps, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:create ]
  end
  resources :bookmarks, only: [:destroy]
  get 'apps/:app_id/bookmark', to: 'bookmarks#create', as: "bookmarkerr"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Google Authentication
  get '/google_oauth2/get_google_access_code', to: 'google_authentications#get_google_access_code'
  get '/google_oauth2/callback', to: 'google_authentications#callback'
end

app/views/apps/_shared_favorite-list.html.erb
<% apps.each do |app| %>
  <div class="col-xs-6 col-sm-4 col-md-2">
    <%= link_to app.webpage_url, target: "_blank" do %>
      <!-- boite principale -->
      <div class="app-card__fav">
        <!-- background box -->
        <div class="app-card__visible" style="background-image: url('<%= app.logo %>')">
          <!-- hovered part -->
        </div>
        <%= link_to app_path(app) do %>
           <%= image_tag 'card-icons/info-icon.png', class: "app-card__hidden fav-icon__info" %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/apps/favorite.html.erb
<div class="main-container">
  <div class="sidebar-container"></div>
  <div class="container">
    <div class="row">
      <div class="col-12 titre fav-header">
        <h2 class="h2">Favorites</h2>
        <div class="btn button clipboard-btn small" aria-label="Copied link to clipboard" data-clipboard-text="<%= ENV['SHARE LINK'] %><%= current_user.public_token %>" > <i class="fas fa-share"></i> &nbsp &nbsp Share
        </div>
      </div>
    </div>
    <% if @apps.present? %>
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item active">
          <a class="nav-link active " id="pills-home-tab" data-toggle="pill" href="#pills-all" role="tab" aria-controls="pills-home" aria-selected="true">All</a>
        </li>
        <% @apps.map { |app| app.category }.uniq.each do |category| %>
          <li class="nav-item">
            <a class="nav-link " id="pills-contact-tab" data-toggle="pill" href="#pills-<%= category.name.gsub(" ", "-") %>" role="tab" aria-controls="pills-contact" aria-selected="false"><%= category.name %></a>
          </li>
        <% end %>
      </ul>
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade active in" id="pills-all" role="tabpanel" aria-labelledby="pills-all-tab">
          <%= render 'shared/favorite-list', apps: @apps %>
        </div>
          <% Category.all.each do |category| %>
            <div class="tab-pane fade" id="pills-<%= category.name.gsub(" ", "-") %>" role="tabpanel" aria-labelledby="pills-<%= category.name.gsub(" ", "-") %>-tab">
              <%= render 'shared/favorite-list', apps: @apps.where(category: category) %>
            </div>
          <% end %>
      </div>
    <% else %>
      <br>
      <p>You don't have any favorite apps yet.</p>
    <% end %>
  </div>
</div>

app/views/apps/index.html.erb
<div class="main-container">
  <div class="sidebar-container"></div>
  <div class="container">
    <% if @featured %>
      <div class="features">
        <div class="grid-features">
          <div class="box-features one-b">
            <%= link_to app_path(App.find_by_name("Slack")) do %>
              <div class="box-features__main" style="background-image: linear-gradient(to top, #ffffff, transparent), url('<%= asset_path "featura-photo.png"%>');">
                <p class="h4">App of the week</p>
              </div>
            <% end %>
          </div>
          <div class="box-features two-b">
            <%= link_to "http://news.cremedelacreme.io/freelance-best-skills-working-freelancer-remote-student-univeristy/", target: "_blank" do %>
              <div class=" box-features__main " style="background-image: linear-gradient(to top, #ffffff, transparent), url('http://news.cremedelacreme.io/content/images/2017/05/image-134.png');">
                <p class="h4"> [Article] 5 skills to developp as a freelance </p>
              </div>
            <% end %>
          </div>
          <div class="box-features three-b">
            <%= link_to "http://news.cremedelacreme.io/best-freelancing-vs-part-time-job/", target: "_blank" do %>
              <div class=" box-features__main " style="background-image: linear-gradient(to top, #ffffff, transparent), url('http://news.cremedelacreme.io/content/images/2018/01/muhammad-raufan-yusup-254422-1.jpg');">
                <p class="h4"> [Article] Freelancing vs Part-time job </p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>



    <div class="row">
        <% if @query %>
          <h2 class="h2">Search results for: "<%= @query %>"</h2>
        <% elsif @category %>
          <h2 class="h2">Category: <%= @category %></h2>
        <% else %>
          <h2 class="h2"> Discover our selection </h2>
        <% end %>
    </div>

    <div class="row">
      <% @apps.each do |app| %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="app-card" id="js-bookmark-hook-<%= app.id %>">
            <div class="app-card__image" style="background-image: url('<%= app.logo %>')"></div>
            <div class="icons-container">
              <% if current_user %>
                <div class="bookmark-container bookmarke<%= current_user.apps.include? app ? 'active' : '' %>">
                  <%= link_to bookmarkerr_path(app), method: :get, remote: :true do %>
                    <% if current_user.apps.include? app %>
                      <i class="fas fa-heart"></i>
                    <% else %>
                      <i class="far fa-heart"></i>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
            <%= link_to app_path(app) do %>
              <div class="app-card__content">
                <div class="app-card__title">
                  <h5><%= app.name %></h5>
                </div>
                <div class="app-card__category-tags-container">
                  <p class="app-card__category">
                    <i class="fas fa-tag"></i> <%= app.category.name %> </p>
                  <p class="bookmarks-nb"> <i class="fas fa-heart"></i> <%= app.bookmarks.count %> </p>
                </div>
                <div class="app-card__description">
                  <p class="short-description"> <%= app.description[0..100] %>...<b> More info</b></p>
                </div>
              </div>
            <% end %>
            </div>
        </div>
      <% end %>
      <div class="col-xs-6 col-sm-4 col-md-3">
        <div class="app-card">
          <div class="app-card__submit-content">
            <div class="app-card___submit-description">
              <p> Didn't find what you're looking for ?</p>
            </div>
            <div class="btn-submit__container">
              <%= link_to new_app_path, class: "button submit-btn app-card__btn" do %>
                Submit an app
              <% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/apps/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 form">
      <h2 class="h2">Submit an app</h2>

      <%= simple_form_for(@app) do |f| %>

        <% if @app.errors.any? %>
          <div class="errors-container">
            <ul>
              <% @app.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-inputs">
          <%= f.input :name,
                      required: true,
                      placeholder: "Add the name",
                      label: false %>

          <%= f.input :webpage_url,
                      required: true,
                      placeholder: "Add the url",
                      label: false %>

          <%= f.input :description,
                      required: false,
                      placeholder: "Add a description",
                      label: false %>

          <%= f.input :category_id,
                      required: true,
                      prompt: "Select a category",
                      label: false,
                      collection: @categories %>

          <%= f.input :logo,
                      label: false %>

          <%= f.input :logo_cache, as: :hidden %>

<!--           <label for="file-upload" class="custom-file-upload">
            <i class="fa fa-cloud-upload"></i> upload the logo
          </label>
          <input id="file-upload" type="file"/> -->

        </div>

        <div class="form-actions">
          <%= f.button :submit, "Submit", class: "form-button button"%>
        </div>
      <% end %>
      <br />
      <p style="font-size: 14px;"> We will get back to you and upload the subimitted app after review. Thank you for your contribution!
      <hr>
        <%= link_to apps_path do %>
          <i class="fa fa-history"></i> Back to Homepage
        <% end %>
    </div>
  </div>
</div>

app/views/apps/shared_apps.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-12">

			<div class="shared-apps__top">
				<div class="shared-apps-name">
					<h2>
			  	 <%= @user.username.capitalize! %>'s Favorite Apps:
			  	 </h2>
			  </div>
				<div>
				  <%= link_to "Save to your favorites", create_multiple_bookmarks_path(apps: @apps.map { |app| app.id }), class: "btn button small" %>
				</div>
			</div>

		</div>

	</div>

	<div class="row">
		<% if @apps.any? %>
			<%= render "shared_favorite-list", apps: @apps %>
		<% else %>
			<h1>no apps dude</h1>
		<% end %>
	</div>
</div>

app/views/apps/show.html.erb
<div class="main-container">
  <div class="sidebar-container"></div>
  <div class="app-show__wrapper">
    <div class="container">
      <div class="row app-show__main-container">

        <div class="col-xs-4">
          <div class="app-show__side ">
            <div class= "app-card__show">
            <div class="app-show__logo" style="background-image: url('<%= @app.logo_url %>');">
              </div>
            </div>
              <%= link_to app_bookmarks_path(@app), method: "post", class: "button app-show__button", remote: true, authenticity_token: true do %>
                  Add to favorites
              <% end %>
              <% if @app.integrated %>
                <%= link_to google_oauth2_get_google_access_code_path(app: @app), class: "button app-show__button" do %>
                  Get real-time info
                <% end %>
              <% end %>
              <%= link_to "More Information", @app.webpage_url, class: "button button-grey app-show__button", target: "_blank" %>
          </div>
        </div>

        <div class="col-xs-8 ">
          <div class="app-show__main">

            <h1 class="app-show__heading"><%= @app.name %></h1>


            <p class="app-show__category"><strong>Category: </strong><%= @app.category&.name %></p>


              <div >
                <% if @app.reviews.present? %>
                <div class="review__average-rating">
                  <strong>Rating: </strong>
                </div>

                  <% @average.times do %>
                      <i class="fa fa-star review__star" aria-hidden="true"></i>
                    <% end %>
                  <% else %>
                    <p style="margin: 0px;"><strong>Rating: </strong>n/a</p>
                  <% end %>

              </div>


            <div class="price-average-wrapper">

              <div>
                <p class="app-show__price">
                  <strong>Price: </strong>
                  <%= link_to "Free", "#", class: "app-show__price" %>
                </p>
              </div>

            </div>


            <p class="app-show__description"><%= @app.description %></p>
            <% if @app.app_screens.present? %>
              <div class = carousel-container>
                <div class="siema">
                  <% @app.app_screens.each do |screen| %>
                    <div>
                      <%= cl_image_tag screen.url_url, class: "app-show__image", width: 600 %>
                    </div>
                  <% end %>
                </div>
                <div class="carousel-button">
                  <button class="prev-screen"> prev</button>
                  <button class="next-screen"> next </button>
                </div>
              </div>
            <% end %>

            <%= simple_form_for [@app, @review] do |f| %>
              <% if @review.errors.any? %>
                <div class="errors-container">
                  <ul>
                    <% @review.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

                <p><strong>Review:</strong></p>

                <div class="star-rating">
                  <input id="star-5" type="radio" name="review[rating]" value="5">
                  <label for="star-5" title="5 stars">
                    <i class="active fa fa-star" aria-hidden="true"></i>
                  </label>
                  <input id="star-4" type="radio" name="review[rating]" value="4">
                  <label for="star-4" title="4 stars">
                    <i class="active fa fa-star" aria-hidden="true"></i>
                  </label>
                  <input id="star-3" type="radio" name="review[rating]" value="3">
                  <label for="star-3" title="3 stars">
                    <i class="active fa fa-star" aria-hidden="true"></i>
                  </label>
                  <input id="star-2" type="radio" name="review[rating]" value="2">
                  <label for="star-2" title="2 stars">
                    <i class="active fa fa-star" aria-hidden="true"></i>
                  </label>
                  <input id="star-1" type="radio" name="review[rating]" value="1">
                  <label for="star-1" title="1 star">
                    <i class="active fa fa-star" aria-hidden="true"></i>
                  </label>
                </div>

              <%= f.input :content, label: false, placeholder: "write your review..."  %>
              <div class="submit-btn-wrapper">
                <%= f.submit "Post your review", class: "button review__button"  %>
              </div>

            <% end %>
            <% if @reviews %>
              <% @reviews.each do |review| %>
                <%= render 'shared/review', review: review %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>